"""phase 5 coaching safety agents pipeline

Revision ID: 14d5a3cd5357
Revises: b7e2f9a4c1d3
Create Date: 2026-07-10 20:36:02.495111
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Any

import sqlalchemy as sa
from alembic import op

revision: str = "14d5a3cd5357"
down_revision: str | None = "b7e2f9a4c1d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Seeded safety_configs v1 (US-H1) — frozen copy of the defaults in
#: docs/safety_workload.md. Canonical code-side constant lives in
#: cricai_coaching.safety_config.DEFAULT_SAFETY_CONFIG; a drift test keeps the
#: two literals equal. Later threshold changes are new versions via the
#: coach-approval-gated API, never edits to this migration.
_SAFETY_CONFIG_SEED_VERSION = 1
_SAFETY_CONFIG_V1: dict[str, Any] = {
    "workload": {
        "age_bands": [
            {"max_age": 11, "weekly_overs_target": [12, 16], "weekly_overs_ceiling": 16},
            {"max_age": 13, "weekly_overs_target": [16, 20], "weekly_overs_ceiling": 20},
        ],
        "balls_per_over": 6,
        "max_bowling_days_per_rolling_7": 4,
        "max_consecutive_day_pairs_per_rolling_7": 1,
        "intensity_weights": {"spin": 1.0, "pace_intent": 1.0, "throwdown": 0.0},
    },
    "batting_split": {
        "daily_balls": 500,
        "blocks": {
            "technical": 150,
            "decision": 150,
            "match_scenario": 100,
            "spin_specific": 50,
            "fun": 50,
        },
        "fun_block_protected": True,
        "deviation_alert_pct": 25,
    },
    "wellness": {
        "pain_escalation_count": 2,
        "pain_escalation_window_days": 14,
    },
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coaching_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_key", "version", name="uq_rule_key_version"),
    )
    op.create_table(
        "drills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("setup", sa.Text(), nullable=False),
        sa.Column("machine_settings", sa.JSON(), nullable=False),
        sa.Column("ball_count", sa.Integer(), nullable=False),
        sa.Column("target_metric", sa.String(length=64), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "technical",
                "decision",
                "match_scenario",
                "spin_specific",
                "fun",
                name="blockintent",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "safety_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "drill_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("plan_date", sa.Date(), nullable=False),
        sa.Column("blocks", sa.JSON(), nullable=False),
        sa.Column("finding_ids", sa.JSON(), nullable=False),
        sa.Column("safety", sa.JSON(), nullable=False),
        sa.Column("safety_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "plan_date", name="uq_plan_player_date"),
    )
    op.create_table(
        "metric_baselines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("zone_key", sa.String(length=64), nullable=False),
        sa.Column("window", sa.String(length=32), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "player_id",
            "metric",
            "zone_key",
            "window",
            "snapshot_date",
            name="uq_baseline_slice_snapshot",
        ),
    )
    op.create_table(
        "rule_overrides",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_key", sa.String(length=64), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "audience",
            sa.Enum("parent", "developer", name="alertaudience", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bowling_ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("balls", sa.Integer(), nullable=False),
        sa.Column(
            "intensity",
            sa.Enum(
                "spin",
                "pace_intent",
                "throwdown",
                name="deliveryintensity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped",
                name="stagestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("detector_context", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("daily", "weekly", "monthly", name="reportkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "published", "blocked", name="reportstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("safety_sha256", sa.String(length=64), nullable=True),
        sa.Column("quality", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "player_id", "kind", "period_start", "period_end", name="uq_report_player_kind_period"
        ),
    )
    op.create_table(
        "wellness_checkins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("checkin_date", sa.Date(), nullable=False),
        sa.Column("soreness", sa.JSON(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("pain", sa.Boolean(), nullable=False),
        sa.Column("pain_note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("agent", sa.String(length=32), nullable=False),
        sa.Column("rule_key", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("condition", sa.JSON(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("effect_size", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("ball_ids", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pain_clearances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("checkin_id", sa.Uuid(), nullable=False),
        sa.Column("cleared_by", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkin_id"],
            ["wellness_checkins.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_stages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped",
                name="stagestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "stage", "attempt", name="uq_stage_run_stage_attempt"),
    )
    op.create_table(
        "report_llm_audits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_key", sa.String(length=64), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence_verdicts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "confirms", "not_supported", name="evidenceverdict", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    # Seed v1 thresholds (hand-written; see module docstring). The fixed id and
    # timestamp keep the migration deterministic across environments.
    op.bulk_insert(
        sa.table(
            "safety_configs",
            sa.column("id", sa.Uuid()),
            sa.column("version", sa.Integer()),
            sa.column("config", sa.JSON()),
            sa.column("approved_by", sa.String(length=64)),
            sa.column("reason", sa.Text()),
            sa.column("created_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": uuid.UUID("c0ffee5a-fe71-4e0f-9a51-000000000001"),
                "version": _SAFETY_CONFIG_SEED_VERSION,
                "config": _SAFETY_CONFIG_V1,
                "approved_by": "bootstrap:docs/safety_workload.md",
                "reason": "Seed defaults from docs/safety_workload.md (US-H1).",
                "created_at": datetime(2026, 7, 10, tzinfo=UTC),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence_verdicts")
    op.drop_table("report_llm_audits")
    op.drop_table("pipeline_stages")
    op.drop_table("pain_clearances")
    op.drop_table("findings")
    op.drop_table("wellness_checkins")
    op.drop_table("reports")
    op.drop_table("pipeline_runs")
    op.drop_table("bowling_ledger_entries")
    op.drop_table("alerts")
    op.drop_table("rule_overrides")
    op.drop_table("metric_baselines")
    op.drop_table("drill_plans")
    op.drop_table("safety_configs")
    op.drop_table("drills")
    op.drop_table("coaching_rules")
    # ### end Alembic commands ###
