"""phase 6 legspin dashboard

Revision ID: 3b86319159fe
Revises: 26ddf8103717
Create Date: 2026-07-11 04:06:55.705186
"""

import uuid
from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Any

import sqlalchemy as sa
from alembic import op

revision: str = "3b86319159fe"
down_revision: str | None = "26ddf8103717"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Seeded app_settings v1 (US-J5 review gate, US-L5 live mode) — frozen copy of
#: the defaults in docs/specs/phase-6-plan.md. Canonical code-side constant lives
#: in cricai_coaching.app_settings.DEFAULT_APP_SETTINGS; a drift test keeps the
#: two literals equal. Later changes are new versions via the approval-gated API,
#: never edits to this migration.
_APP_SETTINGS_SEED_VERSION = 1
_APP_SETTINGS_V1: dict[str, Any] = {
    "report_review": {"mode": "auto_publish", "timeout_hours": 24},
    "live_mode": {
        "enabled": False,
        "allowlist": [
            "ball_count",
            "target_hit_tally",
            "workload_remaining_balls",
            "fatigue_nudge",
        ],
    },
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("approved_by", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "personal_best",
                "volume",
                "streak",
                name="milestonekind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("achieved_on", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "player_id", "kind", "metric", "achieved_on", name="uq_milestone_player_kind_metric_day"
        ),
    )
    op.create_table(
        "coach_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("ball_no", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=64), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "delivery_labels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ball_no", sa.Integer(), nullable=False),
        sa.Column(
            "variation_intent",
            sa.Enum(
                "leg_break",
                "top_spinner",
                "googly",
                "slider",
                "flipper",
                "unknown",
                name="bowlingvariation",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "variation_detected",
            sa.Enum(
                "leg_break",
                "top_spinner",
                "googly",
                "slider",
                "flipper",
                "unknown",
                name="bowlingvariation",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("labeler", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ball_no", name="uq_delivery_label_session_ball"),
    )
    op.create_table(
        "bowling_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=True),
        sa.Column(
            "line",
            sa.Enum(
                "outside_off", "off", "middle", "leg", name="line", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "length",
            sa.Enum("yorker", "full", "good", "short", name="length", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["session_blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "camera_configs",
        sa.Column(
            "role",
            sa.Enum(
                "batting_side",
                "bowling_side",
                "wrist",
                "front_on",
                "other",
                name="camerarole",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
    )
    op.add_column("reports", sa.Column("review_due_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Seed app_settings v1 (hand-written; see module docstring). The fixed id and
    # timestamp keep the migration deterministic across environments.
    op.bulk_insert(
        sa.table(
            "app_settings",
            sa.column("id", sa.Uuid()),
            sa.column("version", sa.Integer()),
            sa.column("settings", sa.JSON()),
            sa.column("approved_by", sa.String(length=64)),
            sa.column("reason", sa.Text()),
            sa.column("created_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "id": uuid.UUID("5e771465-0000-4000-8000-000000000001"),
                "version": _APP_SETTINGS_SEED_VERSION,
                "settings": _APP_SETTINGS_V1,
                "approved_by": "bootstrap:docs/specs/phase-6-plan.md",
                "reason": "Seed defaults from docs/specs/phase-6-plan.md (US-J5/L5).",
                "created_at": datetime(2026, 7, 11, tzinfo=UTC),
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reports", "review_due_at")
    op.drop_column("camera_configs", "role")
    op.drop_table("bowling_targets")
    op.drop_table("delivery_labels")
    op.drop_table("coach_notes")
    op.drop_table("milestones")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
