"""phase 3 events pose metrics

Revision ID: 55dd03e0f4c8
Revises: d2f69c3d37e7
Create Date: 2026-07-07 22:36:39.113192
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "55dd03e0f4c8"
down_revision: str | None = "d2f69c3d37e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ball_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ball_no", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("release_ms", sa.Integer(), nullable=False),
        sa.Column("contact_ms", sa.Integer(), nullable=True),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "auto", "manual", "corrected", name="eventsource", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("detector_version", sa.String(length=64), nullable=False),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ball_no", name="uq_event_session_ball"),
    )
    op.create_table(
        "ball_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ball_no", sa.Integer(), nullable=False),
        sa.Column(
            "phase",
            sa.Enum(
                "pre_release", "contact", "flight", name="metricphase", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ball_no", "phase", name="uq_metrics_ball_phase"),
    )
    op.create_table(
        "clips",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ball_no", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.String(length=8), nullable=False),
        sa.Column("object_key", sa.String(length=255), nullable=True),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "cut", "failed", "gap", name="clipstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ball_no", "camera_id", name="uq_clip_ball_camera"),
    )
    op.create_table(
        "pose_tracks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ball_no", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.String(length=8), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("landmarks_key", sa.String(length=255), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("availability", sa.Float(), nullable=False),
        sa.Column("subject_confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ball_no", "camera_id", name="uq_pose_ball_camera"),
    )
    op.create_table(
        "reference_balls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ball_no", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("marked_by", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ball_no", name="uq_reference_session_ball"),
    )
    op.create_table(
        "event_corrections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["ball_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_corrections")
    op.drop_table("reference_balls")
    op.drop_table("pose_tracks")
    op.drop_table("clips")
    op.drop_table("ball_metrics")
    op.drop_table("ball_events")
    # ### end Alembic commands ###
