"""phase 1 schema

Revision ID: 7f48c10ffa99
Revises:
Create Date: 2026-07-07 17:38:02.019479
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7f48c10ffa99"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "camera_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.String(length=8), nullable=False),
        sa.Column("era_no", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("position_label", sa.String(length=64), nullable=False),
        sa.Column("xyz_offset_m", sa.JSON(), nullable=False),
        sa.Column("height_m", sa.Float(), nullable=False),
        sa.Column("fps", sa.Integer(), nullable=False),
        sa.Column("resolution", sa.String(length=16), nullable=False),
        sa.Column("lens", sa.String(length=64), nullable=False),
        sa.Column("mount", sa.String(length=64), nullable=False),
        sa.Column("protected", sa.Boolean(), nullable=False),
        sa.Column("fov_reference_key", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("camera_id", "era_no", name="uq_camera_era"),
    )
    op.create_table(
        "checklist_acks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("acked_by", sa.String(length=64), nullable=False),
        sa.Column("acked_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("birthdate", sa.Date(), nullable=False),
        sa.Column(
            "handedness",
            sa.Enum("right", "left", name="handedness", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column(
            "session_type",
            sa.Enum(
                "batting", "bowling", "mixed", name="sessiontype", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "bowler_source",
            sa.Enum("machine", "human", "coach", name="bowlersource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("machine_settings", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "created",
                "recording",
                "captured",
                "processing",
                "analyzed",
                "failed",
                name="sessionstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("missing_views", sa.JSON(), nullable=False),
        sa.Column("checklist_ack_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["checklist_ack_id"],
            ["checklist_acks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_blocks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("block_no", sa.Integer(), nullable=False),
        sa.Column("start_s", sa.Float(), nullable=False),
        sa.Column("end_s", sa.Float(), nullable=True),
        sa.Column(
            "bowler_source",
            sa.Enum("machine", "human", "coach", name="bowlersource", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("machine_settings", sa.JSON(), nullable=True),
        sa.Column(
            "intent",
            sa.Enum(
                "technical",
                "decision",
                "match_scenario",
                "spin_specific",
                "fun",
                name="blockintent",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "block_no", name="uq_session_block_no"),
    )
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.String(length=8), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("declared_checksum", sa.String(length=64), nullable=False),
        sa.Column("declared_size", sa.BigInteger(), nullable=False),
        sa.Column("claimed_fps", sa.Float(), nullable=True),
        sa.Column("claimed_resolution", sa.String(length=16), nullable=True),
        sa.Column("claimed_duration_s", sa.Float(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.String(length=8), nullable=False),
        sa.Column("object_key", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("claimed_fps", sa.Float(), nullable=True),
        sa.Column("claimed_resolution", sa.String(length=16), nullable=True),
        sa.Column("claimed_duration_s", sa.Float(), nullable=True),
        sa.Column("codec", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "uploaded",
                "probed",
                "failed",
                "metadata_conflict",
                name="videostatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("probe", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
        sa.UniqueConstraint("session_id", "checksum_sha256", name="uq_video_session_checksum"),
    )
    op.create_table(
        "ball_tags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ball_no", sa.Integer(), nullable=False),
        sa.Column("block_id", sa.Uuid(), nullable=True),
        sa.Column(
            "line",
            sa.Enum(
                "outside_off", "off", "middle", "leg", name="line", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "length",
            sa.Enum("yorker", "full", "good", "short", name="length", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "shot",
            sa.Enum(
                "leave",
                "defend",
                "drive",
                "cover_drive",
                "straight_drive",
                "on_drive",
                "cut",
                "pull",
                "hook",
                "sweep",
                "flick",
                "loft",
                name="shot",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "footwork",
            sa.Enum("front", "back", "leave", name="footwork", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "contact",
            sa.Enum("middle", "edge", "miss", name="contact", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "controlled_ground_shot",
                "controlled_aerial",
                "uncontrolled",
                "beaten",
                "bowled",
                "edged",
                "left_alone",
                name="outcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("control", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("ground_truth_eligible", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["session_blocks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ball_no", name="uq_tag_session_ball"),
    )
    op.create_table(
        "upload_parts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("upload_id", sa.Uuid(), nullable=False),
        sa.Column("part_no", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["upload_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("upload_id", "part_no", name="uq_upload_part"),
    )
    op.create_table(
        "tag_audits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("field", sa.String(length=32), nullable=False),
        sa.Column("old_value", sa.String(length=64), nullable=True),
        sa.Column("new_value", sa.String(length=64), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["ball_tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag_audits")
    op.drop_table("upload_parts")
    op.drop_table("ball_tags")
    op.drop_table("videos")
    op.drop_table("upload_sessions")
    op.drop_table("session_blocks")
    op.drop_table("health_checks")
    op.drop_table("sessions")
    op.drop_table("players")
    op.drop_table("checklist_acks")
    op.drop_table("camera_configs")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
