"""phase 2 calibrations

Revision ID: d2f69c3d37e7
Revises: e036f7af088a
Create Date: 2026-07-07 20:41:20.074968
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d2f69c3d37e7"
down_revision: str | None = "e036f7af088a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibrations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("camera_id", sa.String(length=8), nullable=False),
        sa.Column("era_no", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("intrinsic", "extrinsic", name="calibrationkind", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("rms", sa.Float(), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bounce_marks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("ball_no", sa.Integer(), nullable=False),
        sa.Column("camera_id", sa.String(length=8), nullable=False),
        sa.Column("frame_no", sa.Integer(), nullable=False),
        sa.Column("px_x", sa.Float(), nullable=False),
        sa.Column("px_y", sa.Float(), nullable=False),
        sa.Column("pitch_x", sa.Float(), nullable=False),
        sa.Column("pitch_y", sa.Float(), nullable=False),
        sa.Column(
            "line",
            sa.Enum(
                "outside_off", "off", "middle", "leg", name="line", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column(
            "length",
            sa.Enum("yorker", "full", "good", "short", name="length", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("calibration_id", sa.Uuid(), nullable=True),
        sa.Column("flagged_for_review", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["calibration_id"],
            ["calibrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ball_no", "camera_id", name="uq_bounce_ball_camera"),
    )
    op.add_column("sessions", sa.Column("calibration_id", sa.Uuid(), nullable=True))
    op.add_column(
        "sessions",
        sa.Column("calibration_suspect", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_foreign_key(
        "fk_sessions_calibration_id", "sessions", "calibrations", ["calibration_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_sessions_calibration_id", "sessions", type_="foreignkey")
    op.drop_column("sessions", "calibration_suspect")
    op.drop_column("sessions", "calibration_id")
    op.drop_table("bounce_marks")
    op.drop_table("calibrations")
    # ### end Alembic commands ###
