"""phase1 review fixes: expected_cameras, store_upload_id, storage_usage_samples

Revision ID: e036f7af088a
Revises: 7f48c10ffa99
Create Date: 2026-07-07 18:42:25.226246
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e036f7af088a"
down_revision: str | None = "7f48c10ffa99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_usage_samples",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sampled_on", sa.Date(), nullable=False),
        sa.Column("bytes_used", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sampled_on"),
    )
    op.add_column(
        "sessions",
        sa.Column("expected_cameras", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.add_column(
        "upload_sessions", sa.Column("store_upload_id", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_sessions", "store_upload_id")
    op.drop_column("sessions", "expected_cameras")
    op.drop_table("storage_usage_samples")
    # ### end Alembic commands ###
