/**
 * Every string on the wellness screen (US-H4). The player fills in the
 * check-in unaided, so this copy is kid-facing: plain words, no medical or
 * diagnostic language, and no numbers (the SAF content lint in
 * packages/coaching/tests/test_dashboard_copy_saf.py reads every copy.ts).
 * The only numbers on screen are the API's own values and the form's scale.
 */

export const WELLNESS_COPY = {
  title: "Wellness",
  description: "A quick check-in before practice, and how the body has felt lately.",
  loading: "Loading wellness",
  pickPlayer: "Who is checking in?",
  noPlayersTitle: "No players yet",
  noPlayersDescription: "A parent adds players first, then check-ins can start.",
  loadFailed: "Could not load wellness",
  stateTitle: "Today",
  checkedIn: "Checked in today",
  notCheckedIn: "No check-in today yet",
  daysSince: "Days since last check-in",
  neverCheckedIn: "No check-in recorded yet.",
  painReports: "Recent pain reports",
  painActive: "Pain flag open - an adult needs to look at it.",
  noPain: "No pain flags.",
  bowlingPaused: "Bowling is paused until an adult clears the pain flag.",
  escalation: "Pain has come up several times recently - please talk with your coach and parent.",
  formTitle: "Check in",
  date: "Date",
  energy: "Energy",
  energyHint: "Low to high",
  sleep: "Hours of sleep last night",
  soreness: "Anything feeling sore?",
  sorenessArea: "Body area",
  sorenessLevel: "How sore",
  sorenessLevels: ["not sore", "a little", "sore", "very sore"],
  addSoreness: "Add",
  removeSoreness: "Remove",
  noSoreness: "Nothing sore added.",
  pain: "Something hurts",
  painNote: "Where and how does it hurt?",
  submit: "Save check-in",
  saved: "Check-in saved",
  notSaved: "Check-in not saved",
  fixFirst: "Please fix these first:",
  historyTitle: "Recent check-ins",
  historyEmptyTitle: "No check-ins yet",
  historyEmptyDescription: "Use the check-in form to add the first one.",
  historyEnergy: "energy",
  historySleep: "sleep",
  historySleepUnit: "h",
  historyBy: "by",
  painBadge: "pain",
  openBadge: "open flag",
  clear: "Clear pain flag",
  clearTitle: "Clear the pain flag",
  clearNote: "What was checked, and why it is fine to play",
  clearConfirm: "Clear flag",
  clearCancel: "Cancel",
  clearDone: "Pain flag cleared",
  clearFailed: "Pain flag not cleared",
  clearNoteRequired: "A note is required to clear a pain flag.",
  notRecorded: "not recorded",
} as const;
